import * as ts from "typescript";

export const syntaxKindDefault = [
    ts.SyntaxKind.SourceFile,
    ts.SyntaxKind.FirstStatement,
    ts.SyntaxKind.VariableDeclarationList,
    ts.SyntaxKind.VariableDeclaration,
    ts.SyntaxKind.Identifier,
    ts.SyntaxKind.FirstLiteralToken,
    ts.SyntaxKind.EndOfFileToken,
    ts.SyntaxKind.StringLiteral,
    ts.SyntaxKind.ForStatement,
    ts.SyntaxKind.BinaryExpression,
    ts.SyntaxKind.FirstBinaryOperator,
    ts.SyntaxKind.PostfixUnaryExpression,
    ts.SyntaxKind.Block,
    ts.SyntaxKind.WhileStatement,
    ts.SyntaxKind.TrueKeyword,
    ts.SyntaxKind.IfStatement,
    ts.SyntaxKind.FalseKeyword,
    ts.SyntaxKind.FunctionDeclaration,
    ts.SyntaxKind.ArrayLiteralExpression,
    ts.SyntaxKind.ForOfStatement,
    ts.SyntaxKind.ForInStatement,
    ts.SyntaxKind.ObjectLiteralExpression,
    ts.SyntaxKind.PropertyAssignment,
    ts.SyntaxKind.ArrowFunction,
    ts.SyntaxKind.Parameter,
    ts.SyntaxKind.NumberKeyword,
    ts.SyntaxKind.EqualsGreaterThanToken,
    ts.SyntaxKind.PlusToken,
    ts.SyntaxKind.ExpressionStatement,
    ts.SyntaxKind.CallExpression,
    ts.SyntaxKind.PropertyAccessExpression,
];
